services:
    plejeune.media:
        public: true
        class: PLejeune\MediaBundle\Extension\FileExtension
        arguments: ["@service_container"]
        tags:
            - { name: twig.extension }

    plejeune.media.fileinfo:
        public : true
        class: PLejeune\MediaBundle\Service\FileInfo
        arguments: ["@assets.packages"]
        tags:
            -  { name: twig.extension }

    PLejeune\MediaBundle\Service\FileUpload:
        class: PLejeune\MediaBundle\Service\FileUpload
        arguments: [[], '%kernel.project_dir%']
        public : true
    plejeune.media.fileupload:
        alias: PLejeune\MediaBundle\Service\FileUpload
        public: true

    plejeune.media.command.update:
        public: true
        class: PLejeune\MediaBundle\Command\MediaRefreshCommand
        tags:
            - { name: console.command }
