services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    Darkanakin41\MediaBundle\:
        autowire: true
        public: true
        resource: '../../{Service}'

    Darkanakin41\MediaBundle\Service\:
        autowire: true
        public: true
        resource: '../../Service'

    Darkanakin41\MediaBundle\Twig\:
        autowire: true
        public: true
        resource: '../../Twig'
        tags:
        - { name: twig.extension }
