<?php

/*
 * This file is part of the Darkanakin41MediaBundle package.
 */

namespace Darkanakin41\MediaBundle;

use Doctrine\Bundle\DoctrineBundle\DependencyInjection\Compiler\DoctrineOrmMappingsPass;
use Symfony\Component\DependencyInjection\ContainerBuilder;
use Symfony\Component\HttpKernel\Bundle\Bundle;

class Darkanakin41MediaBundle extends Bundle
{
    public function build(ContainerBuilder $container)
    {
        parent::build($container); // TODO: Change the autogenerated stub

        // With annotation configuration format
        $container->addCompilerPass(DoctrineOrmMappingsPass::createAnnotationMappingDriver([
            'Darkanakin41\MediaBundle\Model'
        ], [
            realpath(__DIR__.'/Model')
        ]));
    }
}
